Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/10/2022

procedimento multiplicaDoisNumeros(a,b: inteiro)
inicio

res <- a * b
fimprocedimento

Var
x, y, res: inteiro


Inicio
x <- 10
y <- 15

multiplicaDoisNumeros(x,y)
escreval(res)

Fimalgoritmo